Returning bytesRead per query as part of searchResult
blevesearch/zapx pull request #142
Opened 2022-11-04 16:34 UTC by Thejas-bhat

2022-11-04 19:48 UTC, abhinavdangeti commented on read.go
> +	// s.incrementBytesRead(metaLen + dataLen)
Why the commented code?

2022-11-04 19:48 UTC, abhinavdangeti commented on read.go
> +	// s.incrementBytesRead(n)
Ditto.

2022-11-07 05:35 UTC, Thejas-bhat commented on read.go
> +	// s.incrementBytesRead(metaLen + dataLen)
Yeah resolving them, my bad.

2022-11-07 17:53 UTC, abhinavdangeti commented
@Thejas-bhat Use bleve_index_api@v1.0.5 and scorch_segment_api@v2.1.4.

2022-11-08 17:25 UTC, abhinavdangeti requested changes
It seems this PR is incomplete.

2022-11-09 16:39 UTC, Thejas-bhat commented
Yeah, fixed the implementation now.

2022-11-09 20:09 UTC, abhinavdangeti approved these changes

2022-11-09 20:10 UTC, merged