sections code for DVS
blevesearch/zapx pull request #166
Opened 2023-07-31 12:39 UTC by Thejas-bhat

work in progress

2023-08-16 15:43 UTC, abhinavdangeti commented
https://github.com/blevesearch/bleve/pull/1869

2023-08-21 21:24 UTC, abhinavdangeti requested changes

2023-08-21 21:24 UTC, abhinavdangeti commented on section_vector_index.go
> +// +build densevector
rename tag to `vectors`

2023-08-21 21:24 UTC, abhinavdangeti commented on new.go
> -
Let's avoid unrelated code changes as much as possible.

2023-08-21 21:24 UTC, abhinavdangeti commented on section_vector_index.go
> +	if vf, ok := field.(index.DenseVectorField); ok {
Recommend refactoring DenseVectorField -> VectorField (as commented in bleve_index_api).

2023-08-21 21:24 UTC, abhinavdangeti commented on section_vector_index.go
> +	//    1. the serialized representation of the dense vector index.
Drop references to "dense" where applicable.

2023-08-21 21:24 UTC, abhinavdangeti commented on section_vector_index.go
> +	vec := field.DenseVector()
API name refactor: DenseVector -> Vector.

2023-09-20 09:35 UTC, metonymic-smokey commented on go.mod
> +replace github.com/blevesearch/bleve_index_api => ../bleve_index_api
Nit: pls remove these replace directives.

2023-09-20 09:36 UTC, metonymic-smokey commented on go.mod
> +replace github.com/blevesearch/bleve_index_api => ../bleve_index_api
I'm guessing you added them for local testing.

2023-10-31 21:00 UTC, abhinavdangeti reviewed
Looking forward to a lot of commentary here :)

2023-10-31 21:00 UTC, abhinavdangeti commented on section_vector_index.go
> +//go:build vectors
Add that copyright snippet above here.

2023-11-02 20:00 UTC, abhinavdangeti approved these changes

2023-11-02 20:00 UTC, merged