MB-59633: Toy: Removed Encoded Value From Vellum and Set DocValues Chunk Mode to 1
blevesearch/zapx pull request #258
Opened 2024-09-03 06:44 UTC by Likith101

2025-03-05 21:59 UTC, abhinavdangeti commented on section_inverted_text_index.go
> +				if !strings.HasPrefix(term, "##") {
Add some commentary around here on what the `##` prefix is for, will you.

2025-03-06 05:27 UTC, CascadingRadium commented on section_inverted_text_index.go
> +				if !strings.HasPrefix(term, "##") {
this will falsely flag any term with the `##` prefix. So if i index a term with `simple` analyzer and the term is `##zapx` it will not index the term.

2025-03-06 05:56 UTC, Likith101 commented on section_inverted_text_index.go
> +				if !strings.HasPrefix(term, "##") {
True, perhaps we could add a length limit here as well as a suffix check. So that only terms with `##asddsa........(100 chars)##` will be filtered. There could still be false positives even with this approach though.

2025-03-06 06:13 UTC, Thejas-bhat commented on section_inverted_text_index.go
> +				if !strings.HasPrefix(term, "##") {
you could perhaps refactor some upstream code to tracking some more info mapping to a fieldID (such as an enum which indicates the field type) and fetch the field type here (=geotype) to make your decision here.

2025-03-06 09:12 UTC, CascadingRadium submitted a review, later dismissed

2025-03-06 09:57 UTC, Thejas-bhat commented on section_inverted_text_index.go
> +	geoShapeFields map[uint16]struct{}
rather than this, I think its better to extend the `fieldsInv` to a struct say fieldInfo or something which will have name and type within it. 

in the getOrDefineField() API you could populate the fieldsInv entry with the type value as well.

That way it would be more future proof (other field types can also leverage this in future if a need comes out) and we don't have the need for an extra member variable either (so lesser objects to maintain by realloc'ing and stuff). 

Please let me know if this sounds better to you all, thanks.

2025-03-07 10:39 UTC, Likith101 commented on section_inverted_text_index.go
> +	geoShapeFields map[uint16]struct{}
I switched the approach so that we store these terms separately and add them only to doc values, let me know if this is better.

2025-03-07 11:19 UTC, CascadingRadium commented on section_inverted_text_index.go
> +	specialTerms map[int]map[int][]byte
since this has only one term that must be added to docValues, rename to `extraDocValueTerm`

2025-03-11 05:48 UTC, Thejas-bhat commented on section_inverted_text_index.go
> +		if f, ok := field.(index.GeoShapeField); ok {
please correct me if i'm wrong here, but this condition block is hit after getting the `analyzedTokenFrequencies` and tracking as part of the postings. So wouldn't the latest patch write the encoded shape to both the term dictionary (since i dont see any checks avoid an insert to the term dictionary downstream) and the doc values section?

2025-03-11 06:33 UTC, Likith101 commented on section_inverted_text_index.go
> +		if f, ok := field.(index.GeoShapeField); ok {
There is a bleve change related to this MB (https://github.com/blevesearch/bleve/pull/2162) that removes the term from the dictionaries as well as the token frequencies.

2025-03-11 09:29 UTC, Thejas-bhat approved these changes

2025-03-11 14:16 UTC, CascadingRadium approved these changes

2025-03-11 17:32 UTC, abhinavdangeti requested changes
@Likith101 do we have confirmation from QE / perf on things looking ok with this change?

2025-03-11 17:32 UTC, abhinavdangeti commented on section_inverted_text_index.go
> +		i.extraDocValues = map[int]map[int][]byte{}
We're creating garbage here that is applicable to geo shape fields _only_, so 2 points here ..

1. the name feels somewhat generic, and should perhaps state what it applies to - like `geoDocValues`?
2. we should move this to line 798.5 above to limit this allocation to geoshape fields only.

2025-03-12 05:13 UTC, Likith101 commented on section_inverted_text_index.go
> +		i.extraDocValues = map[int]map[int][]byte{}
I had kept the name generic so that we can reuse this field for other field types if necessary in the future.

2025-03-12 16:53 UTC, abhinavdangeti commented on section_inverted_text_index.go
> +		i.extraDocValues = map[int]map[int][]byte{}
It's an un-exported attribute, but ok - would you add some commentary around where the var is declared (line 980 below) indicating what it's currently used for.

2025-03-12 16:54 UTC, abhinavdangeti commented
@Likith101 if you could add some more commentary for the map per our conversation^ and testing shows this ok, I'm good to merge this change 👍🏼

2025-03-14 14:41 UTC, abhinavdangeti approved these changes

2025-03-17 05:31 UTC, CascadingRadium approved these changes

2025-03-18 20:38 UTC, abhinavdangeti requested changes

2025-03-18 20:38 UTC, abhinavdangeti commented on section_inverted_text_index.go
> +	extraDocValues map[int]map[int][]byte
Let's change the type of this map to ..
```
extraDocValues map[int]map[uint16][]byte
```

.. to avoid having to re-typecast `fieldID` back to an int in line 802 above.

2025-03-19 14:39 UTC, abhinavdangeti approved these changes

2025-03-19 15:01 UTC, CascadingRadium approved these changes

2025-03-24 22:53 UTC, merged