Toy: Limited Training Size
blevesearch/zapx pull request #274
Opened 2024-10-17 09:30 UTC by Likith101

2026-05-04 12:25 UTC, Likith101 commented
Tested out recall of latency vs latency with limited training using the recall option as the ground truth

Latency => Recall@3: 93.40%	Recall@10: 90.32%	Recall@100: 85.22%
Latency LT => Recall@3: 92.52%	Recall@10: 89.00%	Recall@100: 84.03%

2026-07-28 18:19 UTC, Thejas-bhat requested changes
please resolve the merge conflicts. can you just double check the recall numbers once? also it would be better to make this tunable via bleve/cbft maybe?

2026-07-29 06:22 UTC, Likith101 commented
> please resolve the merge conflicts. can you just double check the recall numbers once? also it would be better to make this tunable via bleve/cbft maybe?

I am not sure if making it tunable helps much. Since a user needs to be very familiar with how this setting can affect things.

When I initially tested, recall numbers seemed to drop by 0.5 with accuracy being the same. Do you want a rerun of the test once again?

2026-08-03 16:01 UTC, Likith101 commented
| Metric | With change | Without change |
|---|---|---|
| Recall@3 | 88.1% | 87.7% |
| Accuracy@3 | 89.3% | 89.3% |
| Index Build Time | 1170.6 | 1581.7 |

2026-08-04 20:17 UTC, Thejas-bhat approved these changes

2026-08-05 06:21 UTC, CascadingRadium approved these changes

2026-08-05 06:21 UTC, merged